description: ""
copyright: "Go Red Team"

# Enable/disable featured images
featuredImages: true

hero:
  video: "/videos/hero-background.mp4"
  title: "Go Red Team"
  subtitle: "Your Trusted Partner in Cybersecurity"

contactData:
  email: "info@goredteam.net"
  phone: "(800) 123-4567"
  address1: "123 Main St"
  address2: "Suite 123"
  city: "Richardson"
  state: "TX"
  zip: "75082"
